/* ─────────────────────────────────────────────
   Seoul Guide 景點資料庫
   cat: 'spot' | 'cafe' | 'restaurant' | 'shopping'
   ───────────────────────────────────────────── */
const GUIDE_SPOTS = [

  // ── 景點 · 建築 · 美術館 ──
  { id: 'amore-hq', cat: 'spot',
    name: 'AmorePacific 本社', nameKo: '아모레퍼시픽 본사',
    district: '龍山',
    addr: '서울 용산구 한강대로 100',
    hours: '平日 09:00–18:00 / 免費',
    img: 'https://images.adsttc.com/media/images/5cb6/90ee/284d/d152/6d00/013f/large_jpg/FEATURE_-923_10_Noshe_180212_N14.jpg',
    tip: 'IG：站在大廳中央往上拍，光線從百葉縫隙切割進來' },

  { id: 'seomun', cat: 'spot',
    name: '西小門殉教聖地歷史博物館', nameKo: '서소문성지 역사박물관',
    district: '中區',
    addr: '서울 중구 칠패로 5',
    hours: '週二–日 09:30–17:30 / 免費',
    img: 'https://thesoulofseoul.net/wp-content/uploads/2025/01/IMG_2907.webp',
    tip: '晴天正午，天光從天窗垂直貫穿，衝擊力極強' },

  { id: 'wongudan', cat: 'spot',
    name: '圓丘壇', nameKo: '원구단 — 大韓帝國天壇遺址',
    district: '中區 · 시청역',
    addr: '서울 중구 소공로 106',
    hours: '全天開放 / 免費',
    img: 'https://www.theseoulguide.com/wp-content/uploads/2019/05/hwangudan_altar_wongudan_altar_seoul_korea.jpg',
    tip: '藏在威斯汀朝鮮飯店庭院，台灣遊客幾乎不知道此地' },

  { id: 'seodaemun', cat: 'spot',
    name: '西大門刑務所歷史館', nameKo: '서대문형무소역사관',
    district: '西大門 · 독립문역',
    addr: '서울 서대문구 통일로 251',
    hours: '週二–日 09:30–18:00 / 成人 3,000₩',
    img: 'https://tong.visitkorea.or.kr/cms/resource/55/3368055_image2_1.jpg',
    tip: '格子窗光影 + 石灰牆，每個角落都是強烈構圖' },

  { id: 'seonjeongneung', cat: 'spot',
    name: '宣陵靖陵', nameKo: '선릉·성릉 — 江南王陵',
    district: '江南 · 선릉역',
    addr: '서울 강남구 선릉로100길 1',
    hours: '09:00–17:30 / 火曜日免費 / 平日 1,000₩',
    img: 'https://upload.wikimedia.org/wikipedia/commons/6/6d/Jeongneung%2C_view_from_the_Hongsalmun-_the_tomb_of_King_Jungjong%2C_at_the_Seonjeonneung_site.jpg',
    tip: '以王陵為前景、玻璃帷幕辦公大樓為背景拍攝' },

  { id: 'craft-museum', cat: 'spot',
    name: '首爾工藝博物館', nameKo: '서울공예박물관',
    district: '鍾路 · 안국역',
    addr: '서울 종로구 율곡로3길 4',
    hours: '週二–日 10:00–18:00 / 常設展免費',
    img: 'https://thesoulofseoul.net/wp-content/uploads/2022/08/IMG_5122.jpg',
    tip: '上午10點前院落光影最美，人也最少' },

  { id: 'leeum', cat: 'spot',
    name: 'Leeum Museum of Art', nameKo: '리움미술관 — 三星文化財團',
    district: '龍山 · 漢南洞',
    addr: '서울 용산구 이태원로55길 60-16',
    hours: '週二–日 10:00–18:00 / 週一休',
    img: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/17/4e/86/leeum-leeum-samsung-museum.jpg?w=1200&h=-1&s=1',
    tip: 'M1、M2、M3三棟建築各由不同大師設計，逐一比對' },

  { id: 'apma', cat: 'spot',
    name: 'APMA 아모레퍼시픽 美術館', nameKo: 'Amorepacific Museum of Art',
    district: '龍山 · 신용산역',
    addr: '서울 용산구 한강대로 100 (본사 내)',
    hours: '週二–日 10:00–18:00 / 免費（特展另計）',
    img: 'https://www.apgroup.com/int/en/resource/images/misc/news/2021-02-23/content/image_2.jpg',
    tip: '結合本社大廳圖書館 + 咖啡廳一起逛一個完美下午' },

  { id: 'light-museum', cat: 'spot',
    name: '光影美學博物館', nameKo: '광영미학박물관 / 빛의시간',
    district: '首爾（展期地點不同）',
    addr: '最新展覽地點請查官網 / IG',
    hours: '依各展場不同，建議提前購票',
    img: 'https://world.seoul.go.kr/wp-content/uploads/2025/07/seoul-light-2025-summer-img-1.jpg',
    tip: '穿白色或素色衣服，光影投影效果最上相' },

  { id: 'ddp', cat: 'spot',
    name: 'DDP 東大門設計廣場', nameKo: '동대문디자인플라자 — Zaha Hadid',
    district: '中區 · 동대문역사문화공원역',
    addr: '서울 중구 을지로7길 2-6',
    hours: '戶外24H / 展覽 10:00–21:00 / 部分免費',
    img: 'https://upload.wikimedia.org/wikipedia/commons/8/8f/Dongdaemun_Design_Plaza_at_night%2C_Seoul%2C_Korea.jpg',
    tip: '入夜後LED燈光矩陣最美，旁邊東大門可夜逛' },

  { id: 'mmca', cat: 'spot',
    name: 'MMCA 國立現代美術館', nameKo: '국립현대미술관 서울관',
    district: '鍾路 · 경복궁역',
    addr: '서울 종로구 삼청로 30',
    hours: '週二–日 10:00–18:00（週五六至21:00）/ 2,000₩',
    img: 'https://www.mmca.go.kr/upload/main/2026/03/2026032010130325612936.jpg',
    tip: '館內咖啡廳在開放式庭院，喝咖啡同時感受空間' },

  { id: 'gyeongbokgung', cat: 'spot',
    name: '景福宮', nameKo: '경복궁 — 朝鮮王朝第一宮',
    district: '鍾路 · 경복궁역',
    addr: '서울 종로구 사직로 161',
    hours: '09:00–18:30 / 3,000₩ / 야간개장名額另購',
    img: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Gwanghwamun_20240413.jpg',
    tip: '7–8月야간개장在官網提前搶票，燈光氛圍完全不同' },

  { id: 'sema', cat: 'spot',
    name: 'SeMA 首爾市立美術館', nameKo: '서울시립미술관 서소문본관',
    district: '中區 · 시청역',
    addr: '서울 중구 덕수궁길 61',
    hours: '週二–日 10:00–20:00 / 免費（特展另計）',
    img: 'https://tong.visitkorea.or.kr/cms/resource/47/3061547_image2_1.png',
    tip: '外牆石柱 + 現代白色展廳，殖民建築再利用教科書' },

  { id: 'ground-seesaw', cat: 'spot',
    name: 'Ground Seesaw Seochon', nameKo: '그라운드시소 서촌 — 西村藝廊',
    district: '鍾路 · 경복궁역',
    addr: '서울 종로구 자하문로7길 (서촌)',
    hours: '週二–日 11:00–19:00 / 免費',
    img: 'https://ak-d.tripcdn.com/images/1mi4g224x98q0qkhvE201.jpg?proc=source/trip',
    tip: '周邊日式民居小巷拍巷弄感，深度不輸北村' },

  { id: 'bukchon', cat: 'spot',
    name: '北村韓屋村', nameKo: '북촌한옥마을 — 600座韓屋的山坡城市',
    district: '鍾路 · 안국역',
    addr: '서울 종로구 가회동 · 계동 일대',
    hours: '全天 / 免費（住宅區，請保持安靜）',
    img: 'https://i.ytimg.com/vi/LiPSw-3C4kE/maxresdefault.jpg',
    tip: '06:00–08:00清晨逛，光線最美且人潮最少' },

  { id: 'changdeokgung', cat: 'spot',
    name: '昌德宮', nameKo: '창덕궁 — UNESCO 世界遺產 · 秘苑',
    district: '鍾路 · 안국역',
    addr: '서울 종로구 율곡로 99',
    hours: '09:00–18:30 / 3,000₩ / 秘苑導覽另行預約',
    img: 'https://tong.visitkorea.or.kr/cms/resource/03/3092503_image2_1.jpg',
    tip: '中文導覽場每週限定，提前一個月在e-ticketing搶票' },

  { id: 'ewha-ecc', cat: 'spot',
    name: '梨花女大 ECC', nameKo: '이화여자대학교 ECC — Dominique Perrault',
    district: '西大門 · 이대역',
    addr: '서울 서대문구 이화여대길 52',
    hours: '全天開放 / 免費',
    img: 'https://images.adsttc.com/media/images/5017/edc1/28ba/0d49/f500/1064/newsletter/stringio.jpg?1414475726',
    tip: '站在地面向下俯拍峽谷，或在底部向上拍玻璃天光' },

  // ── 咖啡廳 ──
  { id: 'serendypiknic', cat: 'cafe',
    name: 'Serendypiknic', nameKo: '세렌디피크닉 — 18盤早午餐',
    district: '龍山 · 원효로',
    addr: '서울 용산구 원효로 186 1층',
    hours: '11:00–23:00 / 中休 15:00–17:00',
    img: 'https://d12zq4w4guyljn.cloudfront.net/750_750_20250221080920_photo3_66668548d3c7.webp',
    tip: 'AmorePacific本社步行可達，可一起規劃' },

  { id: 'cafe-onion', cat: 'cafe',
    name: 'Cafe Onion Anguk', nameKo: '카페 오니언 안국 — 廢棄軍需工廠改建',
    district: '鍾路 · 안국역',
    addr: '서울 종로구 계동길 5',
    hours: '08:00–22:00',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRf5Hyl_WnBtMem76iZ9aMJXKkb5LePrSY5Lg&s',
    tip: '庭院、廊道、斑駁牆面，每個角落都是構圖' },

  { id: 'artist-bakery', cat: 'cafe',
    name: 'Artist Bakery Anguk', nameKo: '아티스트 베이커리 — 鹽麵包聖地',
    district: '鍾路 · 안국역',
    addr: '서울 종로구 안국동 167',
    hours: '07:30起 / 售完為止（通常下午就空了）',
    img: 'https://ugc-images.catchtable.co.kr/catchtable/shopinfo/s-bK5p3ICg-FEAC-fnDi9Nw/c9e9b578cc86471e867e60a8c7d0a249?detail750',
    tip: '07:30開門即有長龍，最晚中午前到達為宜' },

  { id: 'cafe-layered', cat: 'cafe',
    name: 'Cafe Layered 北村', nameKo: '카페 레이어드 북촌 — 司康專門',
    district: '鍾路 · 안국역',
    addr: '서울 종로구 북촌로2길 2-3',
    hours: '平日 08:00–22:00 / 週末 10:00–22:00',
    img: 'https://danielfooddiary.com/wp-content/uploads/2023/06/cafelayered5.jpg',
    tip: '原味司康 + 伯爵茶是經典配法，韓屋窗景構圖極美' },

  { id: 'anthracite', cat: 'cafe',
    name: 'Anthracite Coffee 弘大', nameKo: '앤트러사이트 홍대점 — 1970年代製鞋工廠',
    district: '麻浦 · 홍대입구역',
    addr: '서울 마포구 동교로 211',
    hours: '10:00–22:00',
    img: 'https://images.squarespace-cdn.com/content/v1/51c8b108e4b050e44c477323/1622537576993-HNYFIIRM603EZTVIKXWD/Greysuitcase+Seoul+Cafe+Series+-+Anthracite+Seogyo+%EC%95%A4%ED%8A%B8%EB%9F%AC%EC%82%AC%EC%9D%B4%ED%8A%B8+%EC%84%9C%EA%B5%90%EC%A0%90+01.jpg',
    tip: '生鏽鐵架、混凝土天花板，工業空間感強' },

  { id: 'blue-bottle', cat: 'cafe',
    name: 'Blue Bottle 聖水', nameKo: '블루보틀 성수점 — 韓國最大旗艦店',
    district: '聖水洞 · 성수역',
    addr: '서울 성동구 뚝섬로1나길 11',
    hours: '07:00–20:00',
    img: 'https://kr.bluebottlecoffee.com/cdn/shop/articles/BBCK_SS_main_1600x1600_1e4b79e5-dfab-43d0-a335-49ac4f234cfe.jpg?crop=center&height=420&v=1775009444&width=420',
    tip: '韓國限定 Matcha Oat Latte 必點，工業美學空間' },

  { id: 'highwaist', cat: 'cafe',
    name: 'Cafe Highwaist Ikseon', nameKo: '카페 하이웨스트 익선동 — 韓屋手沖',
    district: '鍾路 · 종로3가역',
    addr: '서울 종로구 수표로28길 (익선동)',
    hours: '11:00–22:00',
    img: 'https://media-cdn.tripadvisor.com/media/photo-m/1280/29/80/bb/73/caption.jpg',
    tip: '窗格透光構圖IG熱門，上午光線最佳' },

  { id: 'coffee-libre', cat: 'cafe',
    name: 'Coffee Libre', nameKo: '커피리브레 — 韓國精品咖啡先驅',
    district: '延南洞 · 홍대입구역',
    addr: '서울 마포구 연남동 (연남점)',
    hours: '11:00–22:00',
    img: 'https://media.timeout.com/images/103077400/750/422/image.jpg',
    tip: '問barista推薦當季手沖豆款，黑板豆款更值得讀' },

  // ── 餐廳 ──
  { id: 'chinois', cat: 'restaurant',
    name: 'Restaurant Chinois', nameKo: '시누아즈 — 法式中菜 × 自然酒',
    district: '延禧洞 · 연희로',
    addr: '서울 서대문구 연희로 32-1',
    hours: '晚間 18:00起 / 建議提前訂位',
    img: 'https://ugc-images.catchtable.co.kr/catchtable/shopinfo/sI5loz9P9IAdwBlPbTuZDpw/m/6d13db75863b4dffae429b12370996e5?resizeType=details500',
    tip: '本地高端夜晚口耳相傳，外國旅客幾乎不知道' },

  { id: 'majang', cat: 'restaurant',
    name: '馬場洞牛肉市場', nameKo: '마장동 축산물시장 — 首爾最大牛肉批發市場',
    district: '城東 · 마장역',
    addr: '서울 성동구 마장로 210',
    hours: '06:00–22:00 / 全年無休',
    img: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0b/38/bf/f2/majang-meat-market.jpg?w=1200&h=-1&s=1',
    tip: '攤位選肉後帶到旁邊燒烤店代烤，費用約 3,000₩/人' },

  { id: 'noryangjin', cat: 'restaurant',
    name: '鷺梁津水產市場', nameKo: '노량진 수산시장 — 清晨海鮮拍賣',
    district: '銅雀 · 노량진역',
    addr: '서울 동작구 노량진로 12',
    hours: '拍賣現場 05:00–06:30 / 市場 24H',
    img: 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Korea-Seoul-Noryangjin_Fish_Market-03.jpg',
    tip: '清晨5點海鮮拍賣現場，首爾最在地的早晨之一' },

  { id: 'gogidang', cat: 'restaurant',
    name: '고기당 肉黨', nameKo: '고기당 — 只賣牛的韓牛燒烤',
    district: '江南（複數分店）',
    addr: '서울 강남 일대',
    hours: '11:30–22:00（中休 15:00–17:00）',
    img: 'https://cdn.prod.website-files.com/6772b615757c5de3138654fc/68c1698ea18dd2b4aaf3433e_Gogidang-00156-1.png',
    tip: '午間套餐是性價比最高的入門選擇' },

  { id: 'sancheong', cat: 'restaurant',
    name: '산청숯불가든 山清', nameKo: '산청숯불가든 — 乙支路傳奇炭火',
    district: '中區 · 을지로3가역',
    addr: '서울 중구 을지로3가 을지로11길 일대',
    hours: '11:00–22:00',
    img: 'https://d12zq4w4guyljn.cloudfront.net/750_750_20260511053133_photo1_16e96d781cd1.webp',
    tip: '平日11:30開門前到是最佳策略，本地人午餐人龍排到門外' },

  { id: 'sinsoldon', cat: 'restaurant',
    name: '신솔돈', nameKo: '新沙洞 生三層肉專門店',
    district: '江南 · 신사역',
    addr: '서울 강남구 신사동 (신사역 도보 5분)',
    hours: '12:00–23:00',
    img: 'https://i.autoreserve.com/thumb/1200x1200/restaurant_image/image/058/953/224/58953224/c46b06f5-dcda-457e-8d77-1f697b2c1341.jpeg?format=webp',
    tip: '겉바속촉 外酥內嫩精髓，搭大蒜片芝麻葉包著吃' },

  { id: 'euljiro', cat: 'restaurant',
    name: '乙支路美食通道', nameKo: '을지로 포장마차 골목 — 首爾最真實庶民夜宵',
    district: '中區 · 을지로3·4가역',
    addr: '서울 중구 을지로3·4가역 일대',
    hours: '18:00後活絡 / 週末最佳',
    img: 'https://thesmartlocal.com/korea/wp-content/uploads/2021/01/Pocha-Streets-in-Seoul-5.jpg',
    tip: '找地下室門口有韓文手寫菜單的，通常不在地圖上' },

  // ── 購物 ──
  { id: 'seongsu', cat: 'shopping',
    name: '聖水洞 성수동', nameKo: '首爾品牌快閃店（팝업스토어）密集地',
    district: '城東 · 성수역',
    addr: '서울 성동구 성수동 (성수역 3번 출구)',
    hours: '各店不同 / 快閃通常週末最完整',
    img: 'https://tong.visitkorea.or.kr/cms/resource/94/2930894_image2_1.jpg',
    tip: '出發前查 wepick.kr 確認當週快閃清單' },

  { id: 'apgujeong', cat: 'shopping',
    name: '狎鷗亭 압구정', nameKo: '首爾最高密度精品 + 韓國設計師聚落',
    district: '江南 · 압구정로데오역',
    addr: '서울 강남구 압구정로 일대',
    hours: '11:00–21:00（各店略異）',
    img: 'https://www.theseoulguide.com/wp-content/uploads/2021/10/apgujeong_rodeo_street_seoul_korea.jpg',
    tip: 'Gentle Monster旗艦店本身就是藝術裝置，不買也值得進去看' },

  { id: 'hyundai-dept', cat: 'shopping',
    name: 'The Hyundai Seoul', nameKo: '더현대 서울 — 重新定義百貨公司的未來型商場',
    district: '永登浦 · 여의도역',
    addr: '서울 영등포구 여의대로 108',
    hours: '10:30–20:00（週末至21:00）',
    img: 'https://images.adsttc.com/media/images/6255/cda3/3e4b/31af/ed00/000b/newsletter/68781-full_889-4_68781_sc_v2com.jpg?1649790355',
    tip: '地下 Eataly + 頂層 Pop-up Zone 是每次必掃的兩個行程' },
];
